### ISSUE TITLE
Auto-searching for machine keys

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#10]
It would be nice if tarsnap-gui could automatically find existing keys.  In particular,
1) I ran the setup wizard
2) I ran it again, with a non-advanced setup, and said I already had a key
3) it prompts me to locate the machine key.  I can manually select ~/.local/share/Tarsnap Backup Inc/blah_2015-06-03-14-46-43 , but it would be nice if it automatically selected this.  (or at least, auto-detected it and asked me to confirm it's the correct key).
(I don't expect the GUI to search every directory, but I think that checking its default directory would be a nice thing to add)

On a related note, I suggest that the keyfiles be named "whatever-aaaa-bb-cc-dd-ee-ff.key"

**Comment by gperciva** [comment]
If something is "on the back-burner", shouldn't it be left open?  I totally agree with the `enhancement` label, and I'd also agree with a `future-version` or `back-burner` label.  But if you close the issue, there's a risk it'll get lost.

**Comment by shinnok** [comment]
If something gets lost or forgotten it means that nobody did get care about it after all, so I wouldn't be worried about this. You are free to add it to the ideas wiki page though.

Shinnok

**Comment by gperciva** [comment]
I'm not certain I understand.  Instead of tracking enhancement issues as an issue, you would prefer to track them on a wiki?

**Comment by cperciva** [comment]
I think the point here is that ideas for new features which tarsnap-gui should include should be tracked the same way as other feature ideas are already being tracked.  Right now that's on https://github.com/Tarsnap/tarsnap-gui/wiki/Ideas, so new items should join that list rather than appearing somewhere else.

**Comment by gperciva** [comment]
ok, done.
