### ISSUE TITLE
Nuke should require typing "No Tomorrow"

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#11]
The command-line app has a nice confirmation screen before deleting all archives:

    $ tarsnap --nuke
    Please type 'No Tomorrow' to continue

I recommend that the GUI implement the same system.

(for the record, deleting a single archive requires no confirmation on the command-line)

**Comment by cperciva** [comment]
There definitely needs to be something to prevent accidental nuking.  Whether it's typing that message or requiring someone to click on a button (which is disabled for the first 5 seconds after the window pops up, and is not selected by default) I'm not so sure... someone who knows more than me about user interface design can figure this out. ;-)

If we go with "No Tomorrow" it might be worth adding more text to the window though.  There's more space in a window than there is on the command line, and we could explain that this will delete all their data.

**Comment by gperciva** [comment]
I favor the "No Tomorrow" confirmation, since you've already used it in the console client, it's simple to type, and not anything a user would type by accident.  I agree with adding more text to the pop-up window.

**Comment by gperciva** [comment]
First draft here: https://github.com/Tarsnap/tarsnap-gui/pull/13

**Comment by shinnok** [comment]
Please also document the current behavior here, in favor of completeness. I don't think Colin knows how it behaves currently, which in my opinion is enough.

**Comment by gperciva** [comment]
Sure.  Current behaviour:

1) click on "Purge archives".

2) A dialogue box pops up saying "Are you sure you want to nuke all archives stored for this key?  Warning: This action cannot be undone.  All archvies will be lost forever.".  This is a standard "question" QMessageBox (with a ? icon), not a "critical" QMessageBox (with the ! icon).
http://doc.qt.io/qt-4.8/qmessagebox.html#details

The user will only realize that this is an important question if she reads and understands the text.  But users do not read text[*].

3) so, I'm a normal user, clicking around randomly, didn't read the text, and clicked "yes".  Now the button says "Purging all archives in 8 seconds... 7 seconds... 6 seconds...".

4) huh, there's a countdown.  That's not a good sign.  I guess I made a mistake, so... quick, hit alt-F4 to exit the app in order to stop this!

When I was writing the patch, I noticed that once the countdown is activated, the tooltip for this button changes to say "Press to Cancel".  That is not sufficient.  If I have made a mistake and there is a countdown before something bad happens, most users are not going to hover their mouse cursor over a button to see if the tooltip has changed.  In testing, it *never* occurred to me to calmly hover my mouse over a button, even though I'd only lose a completely useless 18-byte text file I use for testing tarsnap backups.  Countdowns are panic-inducing, because control is taken away from the user.


[*] It is widely acknowledge that users do not read.
http://uxmyths.com/post/647473628/myth-people-read-on-the-web
http://www.joelonsoftware.com/uibook/chapters/fog0000000062.html
In fact, I'm going to quote from the second page:

    When you design user interfaces, it's a good idea to keep two principles in mind:

        1. Users don't have the manual, and if they did, they wouldn't read it.
        2. In fact, users can't read anything, and if they could, they wouldn't want to.

    These are not, strictly speaking, facts, but you should act as if they are facts, for it will make your
    program easier and friendlier. Designing with these ideas in mind is called respecting the user,
    which means, not having much respect for the user.

If I could only ask one thing of you two with regards to user interfaces, it would be to read that article of Joel's.  Right now, the tarsnap webpage and tarsnap-gui app look like the first "Juno" example in the article.  You're assuming that the user has time, energy, and interest in reading text, and as long as they've read the text, they'll be fine, right?

But that's not the case.  Intelligent people still suffer from cognitive overload; if they are not already familiar with tarsnap, they can easily get confused.  Intelligent people also (sometimes) have children, or cats, or a mother who is badly playing a Bach violin concerto and want them to go practice with her, etc.  People get distracted and make mistakes.  If the mistake is "the app prints some data about an archive that the user doesn't care about", then no big deal -- I mean, it's a sub-optimal user experience, but meh.  But if the mistake is *you lose all your data*, then it behooves us to respect the user by lowering the chance of such a mistake.

(you don't have to read the second blog post from Joel, or the one after that (about Testers), but they wouldn't hurt)

**Comment by cperciva** [comment]
I think the countdown timer is good.  But I agree that users don't read messages and tend to click "yes" or "OK" automatically.  Would it make sense to

1. Ask users to type "No tomorrow" and click on a button labelled "Delete all my data", and then
2. Replace that window with one saying "All of your data will be deleted in <countdown> seconds." with a big "Cancel" button

before the nuke runs?  It seems to me that the natural response from most people to seeing a countdown and a button labelled "Cancel" would be to click that button if they're not absolutely certain about what's happening, which is exactly what we would want.

**Comment by sanbor** [comment]
Maybe you could get "inspired" by Github delete account UX. They ask you to type the name of the repo that you want to delete in order to "enable" the disabled "Delete" button. Go to the Admin page of the repo and try it!

**Comment by gperciva** [comment]
@sanbor : yes, I love that element of the github interface!  It's not exactly applicable in this case, however: "nuke" removes all archives, not only one.  Typing the names of every single archive could be a rather large burden.  (for example, imagine somebody doing daily archives for 6 months, then deciding to stop (or reduce) using Tarsnap!)

I was initially thinking about suggesting this for deleting individual archives, but the length is an important consideration.  Github repos are generally 4-12 characters long [wild guesstimate, no citation], and the names generally make sense (at least to the author).  Some archives names will make sense (for example, mine are "backup-2015-05-15"), but if somebody appends the time as well (for example, the default in the GUI for "append timestamp" is "*_2015-06-11-16:55:57" then typing the full name would be a huge burden (particularly if the minutes:seconds are semi-random).  There are similar options, such as typing the first N characters, or last N characters, which might be a decent compromise.

**Comment by sanbor** [comment]
@gperciva I was thinking in the experience of typing something to get the "Delete" button enabled in order to be able to remove the archive instead of all the mess of a countdown, etc. So how about the exact same UX than Github admin page but instead of typing the name of the repo, having to type something like "delete archive" or "no tomorrow" or "live and let die" or pick random sentences from a funny list of confirmation delete sentences.

**Comment by gperciva** [comment]
@sanbor I think we're talking about two different things.  This "nuke" option means deleting all archives at once, so of course we want to be absolutely certain the user wants this.

I like the idea of "unlocking" the "delete individual archive" function, but that is a separate discussion; I've moved that to issue #22.

**Comment by shinnok** [comment]
Feature integrated.
