### ISSUE TITLE
OSX wizard cowardly refuses to proceed past adding cache & bindir

### ISSUE THREAD

**Issue by dch** [Tarsnap/tarsnap-gui#14]
The wizard won't enable the `proceed` button:

![gyvftbj](https://cloud.githubusercontent.com/assets/284368/8103484/663c6fa2-1018-11e5-9c5d-e9a3f7cef14f.png)

 and it's not clear why.

**Comment by dch** [comment]
OK this is clear to me now but the UI might be more helpful - perhaps a hint, or even checking $PATH and pre-filling the field?

this needs to be the *directory* where tarsnap & tarsnap-* are found.

for brewed tarsnap this will be /usr/local/bin/

**Comment by shinnok** [comment]
The Wizard already looks for both tarsnap and tarsnap-keygen (only the two are used so far by the app) binaries in $PATH. However some desktops/shells, OS X included, don't add /usr/local paths to the ENV by default.  Maybe this is your case?

I made some clarifications in commit 1b3b3465b82e505d0d9140e236b3f0c14bd4b72d, one of them is being more explicit that we're looking for a directory in which the Tarsnap CLI utilities reside and not just the tarsnap binary.
