### ISSUE TITLE
very small bottom margin in dialog windows on Linux

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#144]
In Linux / icewm (and Qt 5.5.1), there's no bottom margin in dialog windows:
![gui-no-bottom](https://cloud.githubusercontent.com/assets/222157/19838826/658fcbc4-9e94-11e6-9578-b34e1b0a6c74.png)

In GNOME (again Qt 5.5.1), there is a margin but it's very small:
![gui-gnome-bottom](https://cloud.githubusercontent.com/assets/222157/19838919/19a08922-9e96-11e6-8a41-cab9b982a5d9.png)

I just checked, and this doesn't happen on OSX.  (I didn't notice the version number, but it's whatever homebrew is currently using)

**Comment by shinnok** [comment]
The OS X style has an implicit margin apparently while the other desktops don't. Adding the bottom margin for footerLayout doesn't affect OS X, but it does fix the issue on Ubuntu for e.g.
