### ISSUE TITLE
add "About" app menu to be more consistent with OSX standards

### ISSUE THREAD

**Issue by dch** [Tarsnap/tarsnap-gui#15]
The version number and often any F/LOSS credits are put into an About menu. The version info is available already today in the app's `help` pane, but it would more typically be found in a separate App Window.

https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html#//apple_ref/doc/uid/20000957-CH29-SW1
https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowPanels.html#//apple_ref/doc/uid/20000957-CH42-SW4

**Comment by shinnok** [comment]
Implemented in c8812bd9566724fe7bed51172bb5e68226c6ce3c. Only added as a menu item for desktops with a native menu bar. For the other ones, a single button "About Tarsnap" that pops up the same window has been added in place of the current items in the Settings -> App category.

@dch Anything else that should be considered for this?
