### ISSUE TITLE
OSX brew consideration

### ISSUE THREAD

**Issue by dch** [Tarsnap/tarsnap-gui#17]
homebrew wants a terminal-based way to test the app, perhaps it could
have a `--help` flag for the binary that prints version number to the
terminal and then exits?

**Comment by dch** [comment]
FWIW a copy of the current brew template here for posterity.

```
class TarsnapGui < Formula
  desc "A GUI for Tarsnap, making online backups for the truly lazy"
  homepage "https://www.tarsnap.com/"
  url "https://github.com/Tarsnap/tarsnap-gui/archive/v0.5.tar.gz"
  sha256 "33009d710ff736900af4f32b063b3635c5b002005c6b7184cb00d5132d5198f9"
  head "https://github.com/Tarsnap/tarsnap-gui.git"

  depends_on "qt5"
  depends_on "tarsnap"

  def install
    system "qmake"
    system "make"
    prefix.install 'Tarsnap.app'
  end

  test do
    system "true"
  end
end
```

**Comment by shinnok** [comment]
I tried to quickly find some info on the terminal test you mentioned, but couldn't find anything relevant quickly. Are you talking about a local system test or the auto build bot?

>  test do
    system "true"
  end

What does this do?

I also found:
>Stuff that builds a .app

Don’t make your formula build an .app (native OS X Application); we don’t want those things in Homebrew. Make it build a command line tool or a library. However, we have a few exceptions to that, e.g. when the App is just additional to CLI or if the GUI-application is non-native for OS X and/or hard to get in binary elsewhere (example: fontforge). Check out the homebrew-cask project if you’d like to brew native OS X Applications.
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md

Which could be a hold back.

**Comment by dch** [comment]
@shinnok yep the test would normally replace the `system "true"` hack I put in.

wrt to the .app I think tarsnap gui would be OK. At worst, the same brew recipe can be hosted anywhere (like my gist) even in the tarsnap-gui project itself.

**Comment by jonafato** [comment]
Per @cperciva's [message](http://mail.tarsnap.com/tarsnap-users/msg01124.html) on the mailing list, binary packages will be available in the future. At that point, [Homebrew-Cask](/caskroom/homebrew-cask) is probably the preferred way of making this installable via brew.

**Comment by shinnok** [comment]
@dch There's now a -v and -h (cfc60c4fbf9b2629117a57616521f0d39f9516f8). Can you please refashion the brew recipe with these new options? :-)

**Comment by dch** [comment]
updated, see above -- works for me -- thanks!!  NB before I can submit this, a new tag is needed with the -v option included. I'll keep an eye out for it ;-)

https://gist.github.com/dch/b39c65038f2b21314dbf

**Comment by shinnok** [comment]
Good. That will be the v0.6 release. Let's wait until that is out.
