### ISSUE TITLE
INSTALL instructions for Redhat-based distros

### ISSUE THREAD

**Issue by phipolis** [Tarsnap/tarsnap-gui#18]
Just wanted to chime in with a version of the INSTALL instructions for Red Hat based distros. This was tested on the current Fedora release (22), but it should work on all fairly recent releases: (Fedora 20+, EL 6+)

1) sudo yum install gcc-c++ git qt5-qtbase-devel
2) git clone https://github.com/Tarsnap/tarsnap-gui.git && cd tarsnap-gui
3) git checkout v0.5 # switch to the desired version
4) qmake-qt5 && make -j$(nproc)
5) ./tarsnap-gui

**Comment by shinnok** [comment]
Thanks! Added to INSTALL in commit 4de9f20a68400fa6b7579387a3dd0083f0dd0d61.
