### ISSUE TITLE
Clicking on a popup notification should navigate the user somewhere

### ISSUE THREAD

**Issue by shawwn** [Tarsnap/tarsnap-gui#208]
For example,

![image](https://user-images.githubusercontent.com/59632/44621475-9dab8c80-a86c-11e8-9e3b-01895b06880d.png)

It's probably fine that the user can't click on this. The popup was a direct consequence of them clicking "Backup."

But the finish message:

![image](https://user-images.githubusercontent.com/59632/44621484-bfa50f00-a86c-11e8-8038-314e676a653b.png)

... should probably take the user to the Archives tab and automatically highlight + click "Display details for this archive."

**Comment by gperciva** [comment]
Hi @shawwn, I added this in #208.

I couldn't think of a specific tab to display if the notification was "you're not online" or "failed to create archive", but the "running" and "completed" messages take you to the archive tab (and in the latter case, shows details about that archive).
