### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [Tarsnap/tarsnap-gui#21]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/Tarsnap/tarsnap-gui/blob/0be7be0ddac7918919325f9ad1eea27065d0e816/src/main.cpp#L4 "main function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "stack unwinding") like they are described by Danny Kalev?

**Comment by shinnok** [comment]
This project doesn't use them, Qt itself doesn't use exceptions, nor does qmake enable them in the generated Makefiles by default. Unless you have a specific issue I'm closing this.

**Comment by elfring** [comment]
How do you think about to care also for a C++ exception like "[std::bad_alloc](http://en.cppreference.com/w/cpp/memory/new/bad_alloc "Allocation failure?")" in your program?
