### ISSUE TITLE
"unlock" the ability to delete individual archives

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#22]
One idea to make individual archive deletion more safe is to "unlock" the functionality before the deletion becomes available.
https://github.com/Tarsnap/tarsnap-gui/issues/11#issuecomment-113174277

**Comment by shinnok** [comment]
If the user selected all archives and hit delete I added an extra step informing him of the existence of the purge/nuke action and offer to cancel or proceed as is. This will act as an extra insurance for dumb behavior as well as expose the purge operation further which should be more efficient.

That extra confirmation dialog only pops up if the number of archives is bigger than a threshold(currently 10). Another extra confirmation dialog(different wording) pops up if the user selected for deletion more than threshold but it's not equal to all archives count for current machine key.

See commit aadf8f3ab6ff9a2d77699e5611327bd294a0f808.

NB:

While having this discussion, keep in mind that we are talking about a desktop application here, so most operations including restore and delete are all fair game, unlike datacenter backups put to cold storage. Asking for typing confirmation to delete *some* or a single archive is over kill. It's not like the user is going to erase his disk. Also keep in mind that this being a GUI application, it should be mostly usable with just a mouse. *Locking* the user from achieving anything in the UI would be wrong in the first place.

**Comment by shinnok** [comment]
Closing this since there's no further feedback on the matter.
