### ISSUE TITLE
debian compile issues with tarsnap-gui

### ISSUE THREAD

**Issue by jungle-boogie** [Tarsnap/tarsnap-gui#24]
Hello,

Please don't hold this against me, but I have a debian based desktop system that I'm trying out with tarsnap and when I got the latest updates, it looks like there's a few compiling errors.

You may see the log here:
https://gist.github.com/jungle-boogie/1f0c4ba2d484960c2c71

**Comment by shinnok** [comment]
You're using the master branch right? Check out the latest commit and retry.

**Comment by jungle-boogie** [comment]
Yes, using master but same messages are appearing.

**Comment by shinnok** [comment]
Can you please try out with the second fix? This should resolve it.

**Comment by jungle-boogie** [comment]
Hi Shinnok,

Much better! Nice work.

Thanks,
jungle

**Comment by shinnok** [comment]
Disclaimer: I do advise you to use the v0.5 version though, master is being actively developed and is a moving target.
If you're using master I'm assuming you are interested in the development process/code or are using some non-released yet feature and thus you know what you're doing. :-)

**Comment by jungle-boogie** [comment]
> If you're using master I'm assuming you are interested in the development process/code or are using some non-released yet feature and thus you know what you're doing. :-)

Right, I'm highly interested in the progress of your project so I'm following head. The compiling issues weren't a big deal but it was great you fixed so quickly.
