### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by contian** [Tarsnap/tarsnap-gui#25]
I have a problem with user login. I can add/modify/delete archives, but I can't add my Tarsnap user to view credit and other information. There's is a way to do this?

I've attached a screenshot (note that _Tarsnap user_ field is inactive!)

Thanks :smile:
_Andrea_

![schermata 2015-07-01 alle 18 38 47](https://cloud.githubusercontent.com/assets/10381001/8459905/9d5a3704-2020-11e5-85d8-be607d5944e2.png)

**Comment by shinnok** [comment]
@contian Yeah, getting account details from the Tarsnap website is not implemented yet. The user field is filled only if the user configured Tarsnap via the Wizard with create new key.

Maybe it would make sense to remove the stuff that's not implemented yet from the UI... it is reminiscent of the original design sketches.

**Comment by contian** [comment]
Ok, thanks!

Unfortunately I'm not a programmer, so I can't help with this project; but if one day Tarsnap GUI includes translations in other languages, I can collaborate for the Italian translation!
