### ISSUE TITLE
unable to unselect a subdir

### ISSUE THREAD

**Issue by swills** [Tarsnap/tarsnap-gui#32]
When picking which items to backup, I want to select my home dir but leave out one subdirectory. However, when I try to do this by clicking the subdirectory, tarsnap-gui unselects all the other things in the dir and selects only the directory I clicked. Is there some way to do this? Or perhaps just exclude certain dirs? Or is this more of a feature request? Thanks!

**Comment by shinnok** [comment]
The QTreeView in use for the FilePicker is severely limited and has many issues, although I tried hard to make it behave as "normal" as possible.

Depending on the use case, it might be best to either make the selections manually or use the "Exclude using shell globbing patterns" functionality that I'm working on right now. This is going to master first of course and will be released along with version 0.7.

**Comment by shinnok** [comment]
Exclude feature pushed in commit 3489c5d11d26b2bf97c4f298d578e9eda024e7b1.

**Comment by swills** [comment]
Thanks! What do you think of doing a release?

**Comment by shinnok** [comment]
My plan is to release v0.7 in the latter part of October, it will include a bunch of nice additions along with the exclude one and some really good fixes and improvements overall. So stay tuned!
