### ISSUE TITLE
Run -j flag headless

### ISSUE THREAD

**Issue by MichaelXavier** [Tarsnap/tarsnap-gui#33]
Running tarsnap-gui with `-j` seems to not spawn a window and instead prints the progress to the terminal, which seems perfect for what is almost certainly the intended use case: running from cron or some such, at least until there's first-party scheduling support.

Unfortunately, in practice running with cron seems to fail for lack of a windowing system: `QXcbConnection: Could not connect to display` Is there some sort of workaround or alternative?

**Comment by shinnok** [comment]
Michael,

Have you tried exporting DISPLAY=:0 in your crontab? That does it for me on Linux, assuming that's what you use.

**Comment by MichaelXavier** [comment]
Sorry about the delay. I'll try that today and let you know.

**Comment by MichaelXavier** [comment]
That did the trick. Maybe this could be in the docs somewhere. Super useful. Thank you!

**Comment by cperciva** [comment]
Is there any way you can check for the -j option before Qt does whatever initialization is causing the error?  Setting DISPLAY is a workaround, but if we're not doing anything graphical it really shouldn't be needed.

**Comment by shinnok** [comment]
The only way would be creating a separate binary that doesn't link QtGui. This could be feasible due to the architecture of the app's backend, maybe later along the road when I have stronger/multiple reasons for it.

This problem is not prevalent on OS X and Windows either.

**Comment by cperciva** [comment]
Ok, this seems like a rather idiotic bug in Qt, but if it's not readily fixable in the application I guess we'll just have to put up with the workaround.
