### ISSUE TITLE
"home directory" button in file browsers

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#39]
The Backup->file browser automatically opens with your home directory, but the Jobs->Add jobs opens with /.  It would be nice if

- it automatically opened with your home directory.
- (possibly) there was a "home dir" button inside that "hamburger menu".  There is a "home" icon in the typical Qt and GNOME file browsers, so users might expect this.

**Comment by shinnok** [comment]
Are you sure the Backup and Jobs pane open by default with different start dirs? Maybe you're misled by the fact that the app remembers the last browse path.
