### ISSUE TITLE
Replace "hamburger" icon with a triangle

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#40]
To the right of the "navigate directories and filter file names" box is a "hamburger" icon (the three horizontal lines).  I know that many websites and apps use this now; I'm not a fan, but that's a personal opinion.

However, that button doesn't actually bring up a pop-up menu (as is done in youtube and firefox, for example).  Instead, it expands a new row in the top portion, displaying checkboxes for "show hidden", "show system", "hide symbolic links".  I suggest that for consistency, the app should use a triangle for this -- that's what the main app uses (for the status messages / console at the bottom of the window).

**Comment by shinnok** [comment]
Done in 8b0441a.
