### ISSUE TITLE
visual warning for "deletion in progress"?

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#41]
Archives->delete archive

Once I select an archive to delete (and press "Yes" in the confirmation), there's a line in the log at the bottom of the screen, but nothing else.  Since the deletion can take a few seconds (even with my tiny test-archives; from reports on the mailing list, it can take much longer for larger "real" archives), the user might think that nothing happened and try deleting the archive again.

It would be great if there was some visual notification in the list... for example, the background of that row could be dark grey, or the archive name could be lighter grey.  Or perhaps even replace the "2.59 MiB  Tuesday..." info with a "(deletion scheduled)" ?

**Comment by shinnok** [comment]
I was planning to turn the items queued for deletion in the list disabled, but now I think changing the detail text would be more self explanatory.

**Comment by shinnok** [comment]
Please take a look at the change above, now I both disable and change detail text. The first is important since it disables further actions on the items to be deleted. If you agree that this is the way to go you can close this issue.

**Comment by gperciva** [comment]
You've disabled the "info" button, but double-clicking on that archive still brings up the details.

**Comment by shinnok** [comment]
Resolved in commit 0ba9c8c.

**Comment by gperciva** [comment]
Fix confirmed.
