### ISSUE TITLE
not usable on 640x480

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#46]
Not certain how serious this is, but the main window doesn't fit into 640x480.  This is primarily noticeable on virtualbox without the extra kernel extensions (which only provides 640x480 pixels).

**Comment by shinnok** [comment]
I can make it go down to approx. 500x400 px, but then this happens:
![screen shot 2016-02-10 at 3 18 24 pm](https://cloud.githubusercontent.com/assets/544446/12948278/b281d9d6-d009-11e5-8687-912f90381589.png)


Which is the reason I restricted the minimum size.

**Comment by gperciva** [comment]
Hmm.  For the record, it looks like MainWindow current has a "preferred" size of 650x610, and a "minimum" size of 600x0 (although evidently other widget(s) have their own minimum height, because I can't make the main window less than 600x535).

By contrast, in Ubuntu 14.04 inside virtualbox with the default (rather poor) desktop system, a maximized xterm is 575x456.  I just tried removing all Tarsnap config and cache dirs, and the GUI app's setup screen has the "Proceed" and "skip wizard" buttons almost off the screen.  If I maximize the screen, I can read those buttons, but then one of the later screens extends off the right-hand side of the visible screen.  In the main app window, it's easy to have it extending beyond (or just cut off -- not certain which) the right-hand side of the screen.

For the record, I am not a fan of Ubuntu.  But they're one of the most popular, if not the most popular, Linux distribution out there.  I think the design needs to be usable on this system.  For example, if there isn't enough horizontal room to have the tabs and the logo, why not move the tabs lower and put the logo on a line by itself?  Or even remove the logo?
(speaking of the logo, the one that shows up in the launcher bar is very low-quality.  Doesn't inspire confidence!)

**Comment by gperciva** [comment]
Also, I should add that supporting lower resolutions is not just a matter of being obsessive-compulsive.  One of my friends is a 56-year-old legal assistant whose eyesight is diminishing (she's had 4 eye checkups in the past 5 months, and is waiting for her next scheduled appointment in 1 month before she can have surgery or a new prescription or something).  Her eyesight has caused her to make costly mistakes at work; she has the Windows "magnification" settings at the maximum, but this means that their old financial software dialogue windows sometimes extend beyond the edge of the screen.  She can generally remember how to enter data on those screens ("hit tab twice, then enter the dollar amount, then tab three times and press enter"), but sometimes she makes mistakes.

I don't think that the Tarsnap app needs to use a huge amount of screen space at any given moment, and I would hate it if users had to guess blindly at what dialog options they were selecting.  So over the next few days I'll be looking for ways of saving GUI space in the app.

**Comment by shinnok** [comment]
Can you try latest master on your desktop again? I made some changes lately that reduce the minimum default size requirements for both the Setup Wizard and the Main windows.

**Comment by gperciva** [comment]
The setup wizard is now usable, but not the main window still does not fit into the available space.  In fact, I can't see the bottom part of the main window at all -- I only see the top portion, then a big white space.

**Comment by gperciva** [comment]
hmm, if I run `tarsnap-gui`, the initial screen looks like it fits (I can see the "Updating archives list from remove... done" line, although the "Help" tab overlaps the logo).  However, if I click the "maximize" button, it goes off the edge of the screen again.

![overlapping](https://cloud.githubusercontent.com/assets/222157/13968817/17d3c3f6-f03c-11e5-9ead-83903594c2c3.png)

I still have things planned to improve the situation, for example, replacing the current "Online backups for the truly paranoid" logo with simply the pancakes logo when the window is narrow, or removing the label entirely (since it doesn't add anything to the program functionality).

**Comment by shinnok** [comment]
If you take a look at latest master, the main window size can go down as low as 600x400px.

**Comment by gperciva** [comment]
Sorry, based on 909bff31, there's still problems.  I added screenshots to #53.

Reminder: the maximum size that a default ubuntu 14.04 inside virtualbox gives us is 575x456.  I'm confident that we can achieve this without sacrificing any usability (maybe not in the next few days, but certainly before version 1.0).

**Comment by shinnok** [comment]
Can we close this one now? I think it should be fixed on master.

**Comment by gperciva** [comment]
The horizontal width fits, but the vertical height does not fit.  The smallest I can make the main window is now 458x**568**, but the space available is 575x**456**.  I'm still moving towards this goal.

**Comment by shinnok** [comment]
@gperciva did you get to reconsider this lately? I think this might be fixed.

**Comment by gperciva** [comment]
No, I haven't gotten to the mainwindow yet.  I'm gradually moving through the widgets, going from smallest to biggest.  :)

At the moment the smallest I can make the main window is **587** pixels, not the 456 which is available.

**Comment by shinnok** [comment]
Take a peek at latest master. The lowest it goes now horizontally is 600. Also the logo icon disappears completely now when width goes bellow that threshold, see screenshot. This is on macOS, when I get to the last round of platform testing for 1.0 release I'll see how it looks on the other desktops.

<img width="483" alt="screen shot 2017-05-17 at 9 11 11 am" src="https://cloud.githubusercontent.com/assets/544446/26140816/87065608-3ae1-11e7-8f29-ed6a254c6aef.png">

**Comment by gperciva** [comment]
> Take a peek at latest master. The lowest it goes now horizontally is 680.

I assume that's an OS X "retina" thing?  On my Linux machine, I see the window as being 341 pixels wide (if I make it as narrow as possible).

**Comment by gperciva** [comment]
The extra margin on top of the tabbar in the screenshot in https://github.com/Tarsnap/tarsnap-gui/issues/46#issuecomment-301996542 looks a bit weird.  Could we consider always using a small icon in the tabbar, as in #53?

**Comment by shinnok** [comment]
Take a look at the last commit. Before removing the logo/icon completely which I like, I'll sit a while with this version. :-)

<img width="557" alt="screen shot 2017-05-22 at 9 29 28 am" src="https://cloud.githubusercontent.com/assets/544446/26295253/b14e2e10-3ed1-11e7-94d6-c6b9d9915b85.png">
<img width="479" alt="screen shot 2017-05-22 at 9 29 16 am" src="https://cloud.githubusercontent.com/assets/544446/26295251/b14b0e2e-3ed1-11e7-9690-11620defcddb.png">
<img width="448" alt="screen shot 2017-05-22 at 9 29 10 am" src="https://cloud.githubusercontent.com/assets/544446/26295252/b14b0082-3ed1-11e7-9a11-d466ade99cf4.png">

**Comment by gperciva** [comment]
I like it; I'll close this issue now.
