### ISSUE TITLE
Credits won't update in the GUI

### ISSUE THREAD

**Issue by bittin** [Tarsnap/tarsnap-gui#47]
Hello, my Tarsnap gui says Credits 0.000000 even if the website says 5.00000

http://imgur.com/a/Pdhg1

**Comment by shinnok** [comment]
What version of the app are you running? I don't see the update button next to the credit.

**Comment by bittin** [comment]
0.6 the latest version that are in the PCBSD tree

**Comment by shinnok** [comment]
That's old, the credits feature wasn't implemented at the time. Latest version is v0.8 released a couple weeks ago. I'll try and reach out to the the PCBSD maintainer for an upgrade.

**Comment by shinnok** [comment]
To my understanding, PC-BSD uses the FreeBSD ports collection and that one includes the latest v0.8 release. Can you try updating your ports collection and see if you get un upgrade for tarsnap-gui?

**Comment by bittin** [comment]
Sure, will try that when i am back at home at work atm

**Comment by shinnok** [comment]
@bittin Any resolution on this? :-)

**Comment by bittin** [comment]
Sorry haven't had time to check this, will try to do it during next week
