### ISSUE TITLE
Failed compilation under Linux Mint 20

### ISSUE THREAD

**Issue by SoloBSD** [Tarsnap/tarsnap-gui#545]
$ sudo QT_SELECT=qt5 qmake && make -j$(nproc)
Updating '/home/memo/tarsnap-gui/resources/translations/tarsnap-gui_en.qm'...
Removing translations equal to source text in '/home/memo/tarsnap-gui/resources/translations/tarsnap-gui_en.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 681 untranslated source text(s)
Updating '/home/memo/tarsnap-gui/resources/translations/tarsnap-gui_ro.qm'...
Removing translations equal to source text in '/home/memo/tarsnap-gui/resources/translations/tarsnap-gui_ro.qm'...
    Generated 591 translation(s) (328 finished and 263 unfinished)
    Ignored 87 untranslated source text(s)
/usr/lib/qt5/bin/uic forms/aboutwidget.ui -o build/gui/ui_aboutwidget.h
/usr/lib/qt5/bin/uic forms/archivelistwidgetitem.ui -o build/gui/ui_archivelistwidgetitem.h
Could not create output file
make: *** [Makefile:1325: build/gui/ui_aboutwidget.h] Error 1
make: *** Waiting for unfinished jobs....
Could not create output file
make: *** [Makefile:1334: build/gui/ui_archivelistwidgetitem.h] Error 1

**Comment by SoloBSD** [comment]
Solved doing 

$ sudo QT_SELECT=qt5 qmake 
$ sudo make -j$(nproc)

**Comment by gperciva** [comment]
Thanks for the update!  `sudo` isn't recommended for compiling, for precisely this type of reason.  The usual set of commands would be
```
QT_SELECT=qt5 qmake
make
sudo make install
```
with `sudo` on only the last command.
