### ISSUE TITLE
console messages on startup

### ISSUE THREAD

**Issue by laneslexicon** [Tarsnap/tarsnap-gui#62]
Just built 0.9 from source on FreeBSD 10.3.
On startup I see a lot of these messages, though everything seems to work ok:

```
Executing command:
[tarsnap --list-archives -vv]
unknown(0): Error creating the PersistentStore: app.appdata not set.
unknown(0): PersistentStore was not initialized properly.
unknown(0): PersistentStore not initialized.
QSqlQuery::prepare: database not open
unknown(0): Driver not loaded Driver not loaded
Command finished with exit code 0 and output:
```

**Comment by shinnok** [comment]
Is this right after setup and then never again? If so they are harmless, though I'll have to silence them in next version.

**Comment by laneslexicon** [comment]
It happens every time.

Tarsnap.conf begins with

[app]
app_data=
backup_list= < a iist of files>


Graeme

**Comment by laneslexicon** [comment]
I removed the old Tarsnap.conf and re-did the setup process and
everything works fine.


I suspect that the first time I ran the software I did something stupid,
probably something to do with permissions. Unfortunately I don't recall
whether I originally used the wizard or tried a manual setup. Either
way, I would be inclined to put this down to user error.


Graeme

**Comment by shinnok** [comment]
Ok. You're free to reopen this ticket if you stumble into it again.
