### ISSUE TITLE
Creating jobs

### ISSUE THREAD

**Issue by laneslexicon** [Tarsnap/tarsnap-gui#66]
When setting up a job using the File System tab I'm not seeing files/directories beginning with ".". It would be useful to have this at least as an option.

I was trying to create a job from an existing archive: it would be convenient to copy the file list  and paste it into the job, but I cannot see any way of doing this.

**Comment by shinnok** [comment]
If you expand the options using the arrow icon to the right of the filter line edit you'll see checkboxes for doing just that. See the picture below.
<img width="582" alt="screen shot 2016-05-10 at 9 40 15 am" src="https://cloud.githubusercontent.com/assets/544446/15148469/65a26af6-1693-11e6-9d9e-96ffa7afa90e.png">

**Comment by shinnok** [comment]
Regarding the file list paste, there's no shortcut like that. I was thinking of having an option for turning the FileTree into a list for Jobs, similar to the Backup list in the first pane I'd assume, so that one can easily review what exactly is selected for a Job and for easier management.

**Comment by laneslexicon** [comment]
What I was trying to do was convert an existing ad-hoc backup into a
repeatable job.

Thanks for the answer about the hidden files - I guess I saw the icon to
the right of the filter and just assumed that it was down-arrow for
combobox.

Graeme

**Comment by shinnok** [comment]
> What I was trying to do was convert an existing ad-hoc backup into a
repeatable job.

Well you can do that in version 0.9! Just use the dropdown on the Backup button the first Backup tab. :-)

**Comment by laneslexicon** [comment]
Sorry, I should have said - convert an existing archive to backup job.
The Backup tab is empty and the backup button disabled.

**Comment by shinnok** [comment]
There's no way for converting an existing archive backup into a Job, only if from the Backup list.

Copying the file list is error prone by the way, since you'll be actually selecting individual files from top to bottom and anything new will be excluded. The only way for truly cloning an existing archive into a Job would be by parsing the original command line stored within the archive and then creating a Job from that.

**Comment by shinnok** [comment]
@laneslexicon I you're satisfied with the answer, can you please close this issue and if not, let us see what else I can do to help you?
